chore: bump CI to use deno 1.36.1 to pick-up DENO_DIR fix
Resolves the issue where deno tries to write to `$HOME` which is read-only:

```
error: Could not create TypeScript compiler cache location: "/home/gitlab-runner/.cache/deno/gen"
```